### ISSUE TITLE
Incorrect BibTeX

### ISSUE THREAD

**Issue by ntraft** [Adamdad/neumeta#2]
Just wanted to point out that the title on the BibTeX is wrong, but here's a more complete BibTeX from Google Scholar:
```
@inproceedings{yang2025neural,
  title={Neural Metamorphosis},
  author={Yang, Xingyi and Wang, Xinchao},
  booktitle={European Conference on Computer Vision},
  pages={1--19},
  year={2025},
  organization={Springer}
}
```

Given issue #1 maybe you need to do a search for any remaining mentions of "Kolmogorov". :-)

Very interesting paper btw! A fun idea.

**Comment by Adamdad** [comment]
Thank you so much!!!! Just revised!!!
